name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      # Install node and npm
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # Cache node_modules
      - name: Run a multi-line script
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      # Build production bundle
      - name: Compile web app
        run: |
          npm install
          ng build --prod
